### ISSUE TITLE
Reproducing main results on QuAC

### ISSUE THREAD

**Issue by zorikg** [JD-AI-Research-NLP/RoR#2]
Hello, 

We really like your work and are interested in reproducing your main results on **QuAC** (including training the model, not only doing inference). 
The readme says that you are currently only open source the code for **TriviaQA**. We wondered when will the code for QuAC be available? 

Thanks

**Comment by pierre-zhao** [comment]
Please refer to https://github.com/pierre-zhao/RoR.
